version: '3'

services:
  myfirstspringbootapp-container:
    image: poojawagh13/my-employee-app:latest
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/myfirstspringbootapp-container
    ports:
      - "8081-8100:8080"
